name: Milestone Summary
on:
  schedule:
    - cron: "0 3 * * 1"
jobs:
  summary:
    runs-on: ubuntu-18.04
    steps:
      - uses: mheap-test/github-action-milestone-summary@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          since: P7D
